// AvconComDefine.h: interface for the AvconComDefine class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_AVCONCOMDEFINE_H__2EE50B51_2BF4_48DF_BEF9_28CD5140D8E2__INCLUDED_)
#define AFX_AVCONCOMDEFINE_H__2EE50B51_2BF4_48DF_BEF9_28CD5140D8E2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//**************************命令**************************
#define 	CONF_COMMAND_CONNECT	0x0001	//请求连接
#define 	CONF_COMMAND_CONNECT_REP	0x8001	//请求连接应答
#define 	CONF_COMMAND_TERMINATE	0x0002	//终止连接
#define 	CONF_COMMAND_TERMINATE_REP	0x8002	//终止连接应答
#define 	CONF_COMMAND_ALL_MCU_INFO	0x0003	//请求所有MCU信息
#define 	CONF_COMMAND_ALL_MCU_INFO_REP	0x8003	//请求所有MCU信息返回
#define 	CONF_COMMAND_BROADCAST_MCU_INFO	0x0004	//MCU信息
#define 	CONF_COMMAND_BROADCAST_MCU_INFO_REP	0x8004	//MCU信息返回
#define 	CONF_COMMAND_CONFERENCE_ALL_INFO	0x0005	//请求会议列表
#define 	CONF_COMMAND_CONFERENCE_ALL_INFO_REP	0x8005	//请求会议列表返回
#define 	CONF_COMMAND_CONFERENCE_ALL_INFO_DATA	0x0006	//会议列表数据
#define 	CONF_COMMAND_CONFERENCE_ALL_INFO_DATA_REP	0x8006	//会议列表数据返回
#define 	CONF_COMMAND_WHITEBOARD_INFO	0x0007	//会议白板信息
#define 	CONF_COMMAND_WHITEBOARD_INFO_REP	0x8007	//会议白板信息返回
#define 	CONF_COMMAND_SCREEN_INFO	0x0008	//会议屏幕信息
#define 	CONF_COMMAND_SCREEN_INFO_REP	0x8008	//会议屏幕信息返回
#define 	CONF_COMMAND_TALKOVER_INFO	0x0009	//会议讨论信息
#define 	CONF_COMMAND_TALKOVER_INFO_REP	0x8009	//会议讨论信息返回
#define 	CONF_COMMAND_WIN_INFO	0x000A	//会议窗口信息
#define 	CONF_COMMAND_WIN_INFO_REP	0x800A	//会议窗口信息返回
#define 	CONF_COMMAND_ASKSPEAKEUSER_INFO	0x000B	//请求发言的信息
#define 	CONF_COMMAND_ASKSPEAKEUSER_INFO_REP	0x800B	//请求发言的信息返回
#define 	CONF_COMMAND_MEDIO_INFO	0x000C	//会议视频信息
#define 	CONF_COMMAND_MEDIO_INFO_REP	0x800C	//会议视频信息返回
#define 	CONF_COMMAND_CONFERENCE_USER_INFO	0x000D	//请求会议的成员基本数据
#define 	CONF_COMMAND_CONFERENCE_USER_INFO_REP	0x800D	//请求会议的成员基本数据返回
#define 	CONF_COMMAND_USER_INFO	0x000E	//成员基本数据
#define 	CONF_COMMAND_USER_INFO_REP	0x800E	//成员基本数据返回
#define 	CONF_COMMAND_VALIDATE_USER	0x000F	//客户端请求验证用户信息
#define 	CONF_COMMAND_VALIDATE_USER_REP	0x800F	//客户端请求验证用户信息返回
#define 	CONF_COMMAND_BROADCAST_LOGIN	0x0010	//广播用户登陆
#define 	CONF_COMMAND_BROADCAST_LOGIN_REP	0x8010	//广播用户登陆返回
#define 	CONF_COMMAND_LOGIN_MCU_REP	0xE010	//用户登陆返回
#define 	CONF_COMMAND_CONFERENCE_INFO	0x0011	//会议基本列表
#define 	CONF_COMMAND_CONFERENCE_INFO_REP	0x8011	//会议基本列表返回
#define 	CONF_COMMAND_LOGIN_CONFERENCE	0x0012	//登陆会议
#define 	CONF_COMMAND_LOGIN_CONFERENCE_REP	0x8012	//登陆会议返回
#define 	CONF_COMMAND_LOGIN_CONFERENCE_MCU_REP	0xE012	//登陆会议返回
#define 	CONF_COMMAND_VIDEO_CARD_INFO	0x0013	//视频卡数据
#define 	CONF_COMMAND_VIDEO_CARD_INFO_REP	0x8013	//视频卡数据返回
#define 	CONF_COMMAND_BROADCAST_NEW_USER_LOGIN_INFO	0x0814	//广播新用户登陆信息
#define 	CONF_COMMAND_BROADCAST_NEW_USER_LOGIN_INFO_REP	0x8814	//广播新用户登陆信息返回
#define 	CONF_COMMAND_ASK_SPEAK	0x0015	//发言请求
#define 	CONF_COMMAND_ASK_SPEAK_REP	0x8015	//发言请求返回
#define 	CONF_COMMAND_BROADCAST_ALLOW_SPEAK	0x0816	//广播允许发言
#define 	CONF_COMMAND_BROADCAST_ALLOW_SPEAK_REP	0x8816	//广播允许发言返回
#define 	CONF_COMMAND_BROADCAST_OPEN_WHITEBOARD	0x0817	//广播打开白板
#define 	CONF_COMMAND_BROADCAST_OPEN_WHITEBOARD_REP	0x8817	//广播打开白板返回
#define 	CONF_COMMAND_BROADCAST_WHITEBOARD_DATA	0x0818	//广播白板动作数据包
#define 	CONF_COMMAND_BROADCAST_WHITEBOARD_DATA_REP	0x8818	//广播白板动作数据包返回
#define 	CONF_COMMAND_BROADCAST_OPEN_SCREEN	0x0819	//广播打开屏幕
#define 	CONF_COMMAND_BROADCAST_OPEN_SCREEN_REP	0x8819	//广播打开屏幕返回
#define 	CONF_COMMAND_BROADCAST_SCREEN_DATA	0x081A	//广播屏幕动作数据包
#define 	CONF_COMMAND_BROADCAST_SCREEN_DATA_REP	0x881A	//广播屏幕动作数据包返回
#define 	CONF_COMMAND_INVITE_USER	0x001B	//邀请已登陆的参会
#define 	CONF_COMMAND_BROADCAST_OPEN_TALKOVER	0x081C	//广播打开讨论区
#define 	CONF_COMMAND_BROADCAST_OPEN_TALKOVER_REP	0x881C	//广播打开讨论区返回
#define 	CONF_COMMAND_TALKOVER_DATA	0x001D	//讨论信息
#define 	CONF_COMMAND_TALKOVER_DATA_REP	0x801D	//讨论信息返回
#define 	CONF_COMMAND_BROADCAST_TALKOVER_DATA	0x081E	//广播讨论信息
#define 	CONF_COMMAND_BROADCAST_TALKOVE_DATA_REP	0x881E	//广播讨论信息返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_WHITEBOARD	0x081F	//广播关闭白板
#define 	CONF_COMMAND_BROADCAST_CLOSE_WHITEBOARD_REP	0x881F	//广播关闭白板返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_SCREEN	0x0820	//广播关闭屏幕
#define 	CONF_COMMAND_BROADCAST_CLOSE_SCREEN_REP	0x8820	//广播关闭屏幕返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_TALKOVER	0x0821	//广播关闭讨论
#define 	CONF_COMMAND_BROADCAST_CLOSE_TALKOVER_REP	0x8821	//广播关闭讨论返回
#define 	CONF_COMMAND_BROADCAST_SCREEN_MODEL	0x0822	//广播改变屏模板
#define 	CONF_COMMAND_BROADCAST_SCREEN_MODEL_REP	0x8822	//广播改变屏模板返回
#define 	CONF_COMMAND_BROADCAST_SET_KINESCOPY	0x0823	//广播设置录像
#define 	CONF_COMMAND_BROADCAST_SET_KINESCOPY_REP	0x8823	//广播设置录像返回
#define 	CONF_COMMAND_BROADCAST_SET_CONTROL	0x0824	//广播设置控制
#define 	CONF_COMMAND_BROADCAST_SET_CONTROL_REP	0x8824	//广播设置控制返回
#define 	CONF_COMMAND_BROADCAST_SET_TALKOVER	0x0825	//广播设置讨论
#define 	CONF_COMMAND_BROADCAST_SET_TALKOVER_REP	0x8825	//广播设置讨论返回
#define 	CONF_COMMAND_BROADCAST_ISSUE_BULL	0x0826	//广播发布公告
#define 	CONF_COMMAND_BROADCAST_ISSUE_BULL_REP	0x8826	//广播发布公告返回
#define 	CONF_COMMAND_INCEPT_VIDEO	0x0027	//接收视频
#define 	CONF_COMMAND_INCEPT_VIDEO_REP	0x8027	//接收视频返回
#define 	CONF_COMMAND_BROADCAST_SET_BROADCAST_VIDEO	0x0828	//广播设广播视频
#define 	CONF_COMMAND_BROADCAST_SET_BROADCAST_VIDEO_REP	0x8828	//广播设广播视频返回
#define 	CONF_COMMAND_SET_VIDEO_CARD	0x0029	//改变视频卡配置
#define 	CONF_COMMAND_SET_VIDEO_CARD_REP	0x8029	//改变视频卡配置返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_INCEPT_VIDEO	0x082A	//广播关闭接收视频
#define 	CONF_COMMAND_BROADCAST_CLOSE_INCEPT_VIDEO_REP	0x882A	//广播关闭接收视频返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_BROADCAST_VIDEO	0x082B	//广播关闭广播视频
#define 	CONF_COMMAND_BROADCAST_CLOSE_BROADCAST_VIDEO_REP	0x882B	//广播关闭广播视频返回
#define 	CONF_COMMAND_INCEPT_SOUND	0x002C	//接收音频
#define 	CONF_COMMAND_INCEPT_SOUND_REP	0x802C	//接收音频返回
#define 	CONF_COMMAND_BROADCAST_SET_BROADCAST_SOUND	0x082D	//广播设广播音频
#define 	CONF_COMMAND_BROADCAST_SET_BROADCAST_SOUND_REP	0x882D	//广播设广播音频返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_INCEPT_SOUND	0x082E	//广播关闭接收视频
#define 	CONF_COMMAND_BROADCAST_CLOSE_INCEPT_SOUND_REP	0x882E	//广播关闭接收视频返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_BROADCAST_SOUND	0x082F	//广播关闭广播视频
#define 	CONF_COMMAND_BROADCAST_CLOSE_BROADCAST_SOUND_REP	0x882F	//广播关闭广播视频返回
#define 	CONF_COMMAND_SET_SOUND	0x0030	//设置音频编码类型
#define 	CONF_COMMAND_SET_SOUND_REP	0x8030	//设置音频编码类型返回
#define 	CONF_COMMAND_ALLOW_KINESCOPE	0x0031	//允许录像
#define 	CONF_COMMAND_ALLOW_KINESCOPE_REP	0x8031	//允许录像返回
#define 	CONF_COMMAND_FORBID_KINESCOPE	0x0032	//不允许录像
#define 	CONF_COMMAND_FORBID_KINESCOPE_REP	0x8032	//不允许录像返回
#define 	CONF_COMMAND_ALLOW_CONTROL	0x0033	//允许控制
#define 	CONF_COMMAND_ALLOW_CONTROL_REP	0x8033	//允许控制返回
#define 	CONF_COMMAND_FORBID_CONTROL	0x0034	//不允许控制
#define 	CONF_COMMAND_FORBID_CONTROL_REP	0x8034	//不允许控制返回
#define 	CONF_COMMAND_SET_ TALK	0x0035	//设置讨论
#define 	CONF_COMMAND_SET_TALK_REP	0x8035	//设置讨论返回
#define 	CONF_COMMAND_BROADCAST_VIDOE_ORDER	0x0836	//广播视频预置
#define 	CONF_COMMAND_BROADCAST_VIDOE_ORDER_REP	0x8836	//广播视频预置返回
#define 	CONF_COMMAND_SUPPORT_CONTRL	0x0037	//云台控制
#define 	CONF_COMMAND_SUPPORT_CONTRL_REP	0x8037	//云台控制返回
#define 	CONF_COMMAND_SET_SUPPORT_PLACE	0x0038	//设置云台预置点设置
#define 	CONF_COMMAND_SET_SUPPORT_PLACE_REP	0x8038	//设置云台预置点设置返回
#define 	CONF_COMMAND_GET_SUPPORT_PLACE	0x0039	//调用云台预置点设置
#define 	CONF_COMMAND_GET_SUPPORT_PLACE_REP	0x8039	//调用云台预置点设置返回
#define 	CONF_COMMAND_OPEN_SHARE_MEDIA	0x003A	//打开共享媒体
#define 	CONF_COMMAND_OPEN_SHARE_MEDIA_REP	0x803A	//打开共享媒体返回
//#define 	CONF_COMMAND_BROADCAST_OPEN_SHARE_MEDIA	0x083B	//广播打开共享媒体
#define 	CONF_COMMAND_BROADCAST_OPEN_SHARE_MEDIA_REP	0x883B	//广播打开共享媒体返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_SHARE_MEDIA	0x083C	//广播关闭共享媒体
#define 	CONF_COMMAND_BROADCAST_CLOSE_SHARE_MEDIA_REP	0x883C	//广播关闭共享媒体返回
#define 	CONF_COMMAND_BROADCAST_CLOSE_BULL	0x083D	//广播关闭公告
#define 	CONF_COMMAND_BROADCAST_CLOSE_BULL_REP	0x883D	//广播关闭公告返回
#define 	CONF_COMMAND_VIDOE_DATA	0x0100	//视频数据发送格式
#define 	CONF_COMMAND_VIDOE_DATA_REP	0x8100	//视频数据发送格式返回
#define 	CONF_COMMAND_SOUND_DATA	0x0300	//音频数据发送格式
#define 	CONF_COMMAND_SOUND_DATA_REP	0x8300	//音频数据发送格式返回
#define 	CONF_COMMAND_BROADCAST_EXIT_SYS	0x0840	//离线
#define 	CONF_COMMAND_BROADCAST_EXIT_CONFERENCE	0x0841	//离开会议

#endif // !defined(AFX_AVCONCOMDEFINE_H__2EE50B51_2BF4_48DF_BEF9_28CD5140D8E2__INCLUDED_)
